# Generated by Django 4.2.5 on 2023-09-10 22:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0002_remove_turnos_horario_profesional_salud_nro_telefono_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesionalsalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('DNI', models.IntegerField(verbose_name='DNI')),
                ('email', models.EmailField(max_length=50, verbose_name='Direccion de correo electronico')),
                ('Nro_telefono', models.IntegerField(blank=True, null=True, verbose_name='Numero de telefono')),
                ('nro_matricula', models.IntegerField(verbose_name='Numero de matricula')),
                ('especialidad', models.CharField(max_length=50, verbose_name='especialidad')),
            ],
        ),
        migrations.AlterField(
            model_name='paciente',
            name='DNI',
            field=models.IntegerField(verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Nro_telefono',
            field=models.IntegerField(verbose_name='Numero de telefono'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(max_length=150, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Direccion de correo electronico'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_de_nacimiento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ocupacion',
            field=models.CharField(max_length=50, verbose_name='Ocupacion/profesion'),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWeb.profesionalsalud'),
        ),
        migrations.AlterField(
            model_name='turnosprofesional',
            name='profesional',
            field=models.ForeignKey(default='a designar', on_delete=django.db.models.deletion.CASCADE, to='appWeb.profesionalsalud'),
        ),
        migrations.DeleteModel(
            name='Profesional_salud',
        ),
    ]
